### ISSUE TITLE
invalid tag <root>

### ISSUE THREAD

**Issue by danielfdsilva** [digidem/osm2obj#7] opened 2017-09-27 10:20 UTC
When trying to convert some `xml` with `strict: true` I'm getting this error: `invalid tag <root>`

I looked around the code and I assume it is happening because a `root` tag is being added here https://github.com/digidem/osm2obj/blob/master/lib/osm2obj.js#L99 but then it fails the check in https://github.com/digidem/osm2obj/blob/master/lib/osm2obj.js#L143 because the `root` tag is not present in `VALID_NODES`.

Is this a bug or am I missing some configuration?

**Comment by gmaclennan** [comment] 2017-09-29 16:26
Hi @danielfdsilva this is a bug, I just found the same problem, caused by https://github.com/digidem/osm2obj/pull/3 - I went and merged after the tests passed, but we must be missing a test for basic functionality. I'll get a chance next week to look at a fix, or can merge a PR before then if you can take a look.

**Comment by gmaclennan** [comment] 2017-10-17 20:29
Should be fixed now.

**Closed as completed by gmaclennan** 2017-10-17 20:29 UTC
